"""fixed relationship3

Revision ID: 0add22c3cfcb
Revises: f3ffbbf17dec
Create Date: 2024-07-11 15:11:52.318917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0add22c3cfcb'
down_revision: Union[str, None] = 'f3ffbbf17dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
