"""isDeleted column in Users table: false replaced by 0

Revision ID: 528538241b34
Revises: d830a64e3486
Create Date: 2024-07-26 10:08:09.929869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "528538241b34"
down_revision: Union[str, None] = "d830a64e3486"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
