"""renamed ProductionParameters table to ProductParameters

Revision ID: 69829f95e3e7
Revises: 0add22c3cfcb
Create Date: 2024-07-12 08:46:28.893578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69829f95e3e7"
down_revision: Union[str, None] = "0add22c3cfcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
