"""Add tokenModel

Revision ID: 88865714c523
Revises: 28bcacddf450
Create Date: 2024-07-15 10:25:37.092381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88865714c523'
down_revision: Union[str, None] = '28bcacddf450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('app_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_Tokens_app_code'), 'Tokens', ['app_code'], unique=False)
    op.create_index(op.f('ix_Tokens_id'), 'Tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tokens_id'), table_name='Tokens')
    op.drop_index(op.f('ix_Tokens_app_code'), table_name='Tokens')
    op.drop_table('Tokens')
    # ### end Alembic commands ###
