"""Renamed app_code to appCode

Revision ID: a034cdf2e676
Revises: 88865714c523
Create Date: 2024-07-15 11:20:04.403630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a034cdf2e676"
down_revision: Union[str, None] = "88865714c523"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Tokens", sa.Column("appCode", sa.String(), nullable=False))
    op.drop_index("ix_Tokens_app_code", table_name="Tokens")
    op.create_index(op.f("ix_Tokens_appCode"), "Tokens", ["appCode"], unique=False)
    op.drop_column("Tokens", "app_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Tokens",
        sa.Column("app_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_Tokens_appCode"), table_name="Tokens")
    op.create_index("ix_Tokens_app_code", "Tokens", ["app_code"], unique=False)
    op.drop_column("Tokens", "appCode")
    # ### end Alembic commands ###
