"""isDeleted column added to ProductParameters table

Revision ID: cba625d035d5
Revises: 2fb0616863fd
Create Date: 2024-07-30 10:58:40.645212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba625d035d5'
down_revision: Union[str, None] = '2fb0616863fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductParameters', sa.Column('isDeleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductParameters', 'isDeleted')
    # ### end Alembic commands ###
