"""Add unique constraint to code column in ProductionParameters

Revision ID: efa48127cedd
Revises: ed5c0e40271e
Create Date: 2024-07-11 13:59:34.096573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa48127cedd'
down_revision: Union[str, None] = 'ed5c0e40271e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ProductionParameters', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProductionParameters', type_='unique')
    # ### end Alembic commands ###
